'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class celulas
    Public Property IdCelula As Long
    Public Property IdLider As Nullable(Of Long)
    Public Property IdAnfitrion As Nullable(Of Long)
    Public Property FechaRealizacion As Nullable(Of Date)

End Class
