'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class miembros
    Public Property Id As Long
    Public Property IdPadre As Nullable(Of Long)
    Public Property PNombre As String
    Public Property SNombre As String
    Public Property PApellido As String
    Public Property SApellido As String
    Public Property NumCelular As String
    Public Property CompaniaCelular As String

End Class
