'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SistemaBethelEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SistemaBethelEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property celulas() As DbSet(Of celulas)
    Public Overridable Property miembros() As DbSet(Of miembros)
    Public Overridable Property reportes() As DbSet(Of reportes)
    Public Overridable Property v_miembros() As DbSet(Of v_miembros)

End Class
