'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class reportes
    Public Property Id As Long
    Public Property IdCelula As Nullable(Of Long)
    Public Property Hermanos As Nullable(Of Integer)
    Public Property Invitados As Nullable(Of Integer)
    Public Property Ninos As Nullable(Of Integer)
    Public Property Conversiones As Nullable(Of Integer)
    Public Property Reconcilios As Nullable(Of Integer)
    Public Property BAgua As Nullable(Of Integer)
    Public Property BEspiritu As Nullable(Of Integer)
    Public Property Ofrenda As Nullable(Of Decimal)
    Public Property Encuentristas As Nullable(Of Integer)
    Public Property Fecha As Nullable(Of Date)

End Class
